Remake cardapio
DevMobUFRJ/BandejApp pull request #11
Opened 2023-07-26 07:23 UTC by leaaaaaao

Muita muita coisa

2023-07-27 13:02 UTC, carloseduardobanjar requested changes

2023-07-27 13:02 UTC, carloseduardobanjar commented on src/Components/Dia/index.tsx
>              <Menu style={{display: hora===0? 'flex':'none'}}>
no meu celular, o comprimento de menu está levemente menor que a div do glúten

![gluten](https://github.com/DevMobUFRJ/BandejApp/assets/57270830/193048c8-d244-46c2-8375-a8deb4d1d157)

2023-07-27 17:03 UTC, leaaaaaao commented on src/Pages/Cardapio/index.tsx
> +                    if ((abrindo && opacidade < 1) || !abrindo && opacidade > 0)
Jurava que já tinha mudado isso, vou corrigir

2023-07-31 01:50 UTC, carloseduardobanjar approved these changes

2023-07-31 02:32 UTC, merged